extensions:
    enabled:
        - tad\WPBrowser\Extension\Symlinker
    config:
        tad\WPBrowser\Extension\Symlinker:
            mode: "plugin"
            destination: "/var/www/html/wp-content/plugins"
            rootFolder: "/usr/local/src/config/plugins/%SYMLINK_FOLDER%"
