extensions:
    enabled:
        - tad\WPBrowser\Extension\Symlinker
    config:
        tad\WPBrowser\Extension\Symlinker:
            mode: "theme"
            destination: "/var/www/html/wp-content/themes"
            rootFolder: "/usr/local/src/config/themes/%SYMLINK_FOLDER%"
