actor: Tester

paths:
    tests:   tests
    log:     tests/_output
    data:    tests/_data
    helpers: tests/_support
    envs:    tests/_envs
params:
    - env # Load parameters from environment variables

extensions:
    commands:
        - 'Codeception\Command\GenerateWPUnit'
        - 'Codeception\Command\GenerateWPRestApi'
        - 'Codeception\Command\GenerateWPRestController'
        - 'Codeception\Command\GenerateWPRestPostTypeController'
        - 'Codeception\Command\GenerateWPAjax'
        - 'Codeception\Command\GenerateWPCanonical'
        - 'Codeception\Command\GenerateWPXMLRPC'

modules:
    config:
        WPLoader:
            # Database settings
            dbName:         '%DB_NAME%'
            dbHost:         '%DB_HOST%'
            dbUser:         '%DB_USER%'
            dbPassword:     '%DB_PASSWORD%'
            tablePrefix:    '%WP_TABLE_PREFIX%'
            wpRootFolder:   '%WP_ROOT_FOLDER%'
            domain:         '%WP_DOMAIN%'
            adminEmail:     '%ADMIN_EMAIL%'

        WPDb:
            dsn:            'mysql:host=%DB_HOST%;dbname=%DB_NAME%'
            user:           '%DB_USER%'
            password:       '%DB_PASSWORD%'
            url:            '%WP_URL%'
            populator:      'mysql -u $user -p$password -h $host $dbname < $dump'
            dump:           'wp-content/mysql.sql'
            populate:       true
            cleanup:        true
            urlReplacement: true
            tablePrefix:    '%WP_TABLE_PREFIX%'

        WPBrowser:
            url:            '%WP_URL%'
            adminPath:      '/wp-admin'
            adminUsername:  '%ADMIN_USERNAME%'
            adminPassword:  '%ADMIN_PASSWORD%'

        WPCLI:
            path:           '%WP_ROOT_FOLDER%'

        WPFilesystem:
            wpRootFolder:   '%WP_ROOT_FOLDER%'
